version: '3.8'

services:
  backend:
    build:
      context: ../
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
    depends_on:
      - postgres
      - redis
    networks:
      - my-app2-network

  frontend:
    build:
      context: ../
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ../:/app
    depends_on:
      - backend
    networks:
      - my-app2-network

  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - my-app2-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - my-app2-network

volumes:
  postgres_data:

networks:
  my-app2-network:
    driver: bridge
